[[Minuit2_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a580f5bcd700801bb2033d4108cff412b9ad1dde"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "8454ab13b8cce251248e0021edbe6cb82377d7d94f9455b0d9c2bb0b0c9c54ba"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.aarch64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e40b4d559284f5b9325dc6f1b85f4302f59e83c7"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "690fedcdfb969faba9b6fd48e46737163cac0391d37e5b7a43fb8d56e58faa9d"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.aarch64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dfa6f09c9a0876144922c4b2848d9e10bb63a8b4"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "12c6f1b99bf582b1b4dcabe1775d0934a3376341e995d40531db0db5f74140c6"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.aarch64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9e22ff6700e2ee30596a1b9b507ac15cc5d08cf"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "924da6bc12407adfe1f935af3d68f314187e59a20946554659be2fa3a2c586ba"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.aarch64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ba51b7427999c923412d946bb3000b08ba3fc4a2"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "7c7ef1b50ae4b60ca26b0b8e70e7e30453c00e7e7ce1f5d7a5d4dcc8d2fb6f3f"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.armv7l-linux-gnueabihf-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21f420d14beeb55d66527ee13ebdcf00d5e1c992"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "1420fd79bbc390e0c13a6d32ded98735701db192ef798bc63433756d563e7262"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.armv7l-linux-gnueabihf-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5df797492afeb6c85530908aba24014bc0f22aac"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "61ff3389ebdbc3b27d7466ff9658d6fe66688c472f6d078ecb2e81e1dbc2b096"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.armv7l-linux-musleabihf-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb4a0b68eab0d233e88e49467adaea488527f5a0"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "70d01896cee8c305fd85846795b20b3ecaedaec5845aca532d1ae4530e2d1b04"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.armv7l-linux-musleabihf-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c5e0c666fda7d3cffe50c28cdbe9235eae7766d"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "0c55a6ec95066410dfbdd211aa9b678bf1f00ffa7b42b05f50ac022fef957db2"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.i686-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "528add926e8a70f3e57813bf6d8ec37dab412fdc"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "e933ff4ab88b3b8acf5b36fb693942ea41be653c91f40610fafddeb534b4ed5d"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.i686-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea4dd3bcc0d59b70e1577beaa23098b8cd43892e"
julia_version = "1.5.3"
os = "windows"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "93bd1fe533a836e61a7be4a1f484f45d2cd8b9ef165f96031a2483abaeb90083"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.i686-w64-mingw32-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0549fa9153fa4994bb6ae2ffd14c9ffb47642e74"
julia_version = "1.5.3"
os = "windows"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "f116e49c8c20d20abfd04fd51c360dedbd0af5acf9c9b760e4a7c0582b0c5133"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.i686-w64-mingw32-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc982f2684aa22f42fff7a3a1fb9c61fa7b13943"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "8f4dfdd964780978933e4f255b7c87d0fce6471d541882c05f7660b636238fa8"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.powerpc64le-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "026c1a29c37517c31a242db16485c0bdc73b9e07"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "534cff718ac7f9cd78f3e49082abdb24de974e65880db322b26c82c8cc7505e3"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.powerpc64le-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "5acfd1dbc4042daf6dddd72a6ab9fe8ae9ba52f0"
julia_version = "1.5.3"
os = "macos"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "c68d78dc1c832fd9f4ef2fad5cf1b4f88c68e325d2aa1240ba20eb765356ae7b"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-apple-darwin-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "113e80526b4d9c3181618c3e5fa96c79e9c5d9d6"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "89874158a37d1084c776842db82ab218831f7ac31393b2a2d8d43bcf491a6d4d"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-linux-gnu-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "233d3e7ec7b2197b6d2252910ca95edfa45492d9"
julia_version = "1.5.3"
libc = "glibc"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "4f2c1a4d8f95141aa34e63eb00d4bd9e590cba4f2f4b7a203e6d8e3fd8db4d6c"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-linux-gnu-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04f623f844a4001a3cfd259dd2e091f1c5cca1b2"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "e00d254e60cb78cb0d664a055ca148fa058b4eef5f9df29e08b8558318ace65d"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-linux-musl-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a3aec6c0d05436301a3bc79ed63e7b768fb7190"
julia_version = "1.5.3"
libc = "musl"
os = "linux"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "c8a16926f094f2a036647880b110c60d9e9f3a3164807e3ab4b2c27b98036394"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-linux-musl-cxx11-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "c6ffeda5e361605772e7e85a38eff93cf5d7ee13"
julia_version = "1.5.3"
os = "freebsd"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "005db4ebc885717002350a25ef5f2732c05f58da5ff34dbb371226dd4ae23ee5"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-unknown-freebsd-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6ea4e7741748465bfbebbd97938bf1733a56746"
julia_version = "1.5.3"
os = "windows"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "cc09257e43fd9ba34ba5c3cc86b02ce5d41fef379aba30d745f6f7d270208cf9"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-w64-mingw32-cxx03-julia_version+1.5.3.tar.gz"
[[Minuit2_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78f5ce6083b33688d071a499c27d475e4500ce33"
julia_version = "1.5.3"
os = "windows"

    [[Minuit2_Julia_Wrapper.download]]
    sha256 = "682fe217cf12535299ebf00834c14cb3628a45dc0adacf8948279daad82efe34"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_Julia_Wrapper_jll.jl/releases/download/Minuit2_Julia_Wrapper-v0.1.0+1/Minuit2_Julia_Wrapper.v0.1.0.x86_64-w64-mingw32-cxx11-julia_version+1.5.3.tar.gz"
