# Autogenerated wrapper script for Minuit2_Julia_Wrapper_jll for x86_64-apple-darwin
export minuit2wrap

using libcxxwrap_julia_jll
using Minuit2_jll
JLLWrappers.@generate_wrapper_header("Minuit2_Julia_Wrapper")
JLLWrappers.@declare_library_product(minuit2wrap, "@rpath/libminuit2wrap.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, Minuit2_jll)
    JLLWrappers.@init_library_product(
        minuit2wrap,
        "lib/libminuit2wrap.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
